### ISSUE TITLE
Saapadu mukiyum Bigil uh....

### ISSUE THREAD

**Issue by pravynragav** [V1GNE5H05/canteen#2]
Reminder!

**Comment by V1GNE5H05** [comment]
praveenu....oru help da...

ennoda suitcase mela, illa table, illa na cupboard la arish muthaiah voda java assignment irukkum....adha en class karen prasana kumar kitta mattum eduthu kuduthuru da

mam submit panna sonnanga, naalaikku morning poi avana submit panna solliru da

**Comment by V1GNE5H05** [comment]
ippo vey sollu da

**Comment by V1GNE5H05** [comment]
illa da...solla venam

**Comment by pravynragav** [comment]
Enna vikki solra
note ah kudukava

**Comment by V1GNE5H05** [comment]
Ila venam da

**Comment by V1GNE5H05** [comment]
Dei...prasan Kumar kitta avanoda digital principal assignment naalikula
submit pannanum nu mattum solliru da

**Comment by pravynragav** [comment]
Hmm ok da
room no enna

**Comment by V1GNE5H05** [comment]
Balaji room ku pakkathu room ...bathroom pakkathula

**Comment by pravynragav** [comment]
Ok

**Comment by pravynragav** [comment]
vikki innaiku sapadu vangitu vanthena bag kulla vach kondu va 
dress kulla may be gate la kekalam
